### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ExordiumX** [c-um/discordexperiments#1]
```
VM511:5 Uncaught TypeError: Cannot read property 'nodes' of undefined
    at <anonymous>:5:72
```

**Comment by c-um** [comment]
Appears they may have patched it, it was working when I've uploaded this..

**Comment by c-um** [comment]
Pushed the updated version of the enabler, DIscord is really trying to prevent this from happening lol

**Comment by kelvinlai92** [comment]
Don't trust this scammer

**Comment by c-um** [comment]
> Don't trust this scammer

What? lol
